#!/usr/bin/env bash

# Delete unused images tagged as <none>
docker images --no-trunc | grep '<none>' | awk '{ print $3 }'  | xargs docker rmi

# Delete unused containers
docker ps --filter status=dead --filter status=exited -aq  | xargs docker rm -v

# Delete unused volumes
docker volume ls -qf dangling=true | xargs docker volume rm
